// This file is automatically generated and contains assets from optimism.
// Generate for other networks by running: yarn generate-assets [network].
// Supported networks are: arbitrum, goerli, mainnet, and polygon.

import { Address } from '@graphprotocol/graph-ts';

class Assets {
  public stableAssets: Address[];
  public pricingAssets: Address[];
  public fxAssets: Address[];
  public fxAggregators: Address[];
}

export const USDC_ADDRESS = Address.fromString('0x7F5c764cBc14f9669B88837ca1490cCa17c31607');
export const DAI_ADDRESS = Address.fromString('0xDA10009cBd5D07dd0CeCc66161FC93D7c9000da1');
export const USDT_ADDRESS = Address.fromString('0x94b008aA00579c1307B0EF2c499aD98a8ce58e58');

export const assets: Assets = {
  stableAssets: [
    Address.fromString('0x7F5c764cBc14f9669B88837ca1490cCa17c31607'), // USDC
    Address.fromString('0xDA10009cBd5D07dd0CeCc66161FC93D7c9000da1'), // DAI
    Address.fromString('0x94b008aA00579c1307B0EF2c499aD98a8ce58e58'), // USDT
  ],
  pricingAssets: [
    Address.fromString('0x4200000000000000000000000000000000000006'), // WETH
    Address.fromString('0x9Bcef72be871e61ED4fBbc7630889beE758eb81D'), // rETH
    Address.fromString('0x1F32b1c2345538c0c6f582fCB022739c4A194Ebb'), // wstETH
  ],
  fxAssets: [
  ],
  fxAggregators: [
  ],
};
